version: '2' # specify docker-compose version

# Define the services/containers to be run
services:
  angular: # name of the first service
    volumes:
      - ./angular-client:/usr/src/app
    build: angular-client # specify the directory of the Dockerfile
    ports:
      - "4200:4200" # specify port forwarding

  express: #name of the second service
    build: express-server # specify the directory of the Dockerfile
    ports:
      - "3000:3000" #specify ports forwarding
    links:
      - elasticsearch1
    volumes:
      - ./express-server:/usr/src/app

  elasticsearch1:
    image: docker.elastic.co/elasticsearch/elasticsearch:5.4.0
    container_name: elasticsearch1
    environment:
      - cluster.name=docker-cluster
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    mem_limit: 1g
    volumes:
      - esdata1:/usr/share/elasticsearch/data
      - ./elastic-search/config/elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml
    ports:
      - 9200:9200

volumes:
  esdata1:
    driver: local
